% test build_triangulation_from_edg_list

clc;


addpath(genpath('../../src'));
addpath('../../data');


filenames = {'tetrahedron';...
             'cube';...
             'octahedron';...
             'icosahedron';...
             'dodecahedron';...
             'dodecahedron2';...
             'disk';...
             'torus_light';...
             'torus';...
             'geoid_lvl_16';...
             'meshed_mtlb_logo';...
             'kitten';...
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k';...             
             };

         
id = 8;
filename = strcat(cell2mat(filenames(id,1)),'.mat');         
load(filename);

% Randomly mess up the edge set
E = query_edg_list(T);
new_id = randperm(size(E,1));
E = E(new_id,:);
E = fliplr(E);

clear T;

% Rebuild the mesh
T = build_triangulation_from_edg_list(E);
plot_mesh(V,T);