% test compute_mesh_curvature

clear all, close all, clc;

addpath('../src');
addpath('../data');


filenames = {'Reuleaux_tetrahedron';...
             'sinico';...                   
             'torus_light';...
             'torus';...                          
             'kitten';...
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k';...
             'bunny_16k';...
             'Cthulhu_skull'};
                 
% 'sinus_dodeca';...       
% 'log_spiral';...
% 'Archimede_spiral';...
% 'Fermat_spiral';...         

filename = strcat(cell2mat(filenames(9,1)),'.mat');         
load(filename);

ngb_degre = 1;
N = compute_vertex_normals(V,T,ngb_degre,'raw');
curvature = compute_mesh_curvature(V,T,N,ngb_degre,'mean');
show_mesh_curvature(V,T,curvature);