% test oversample_mesh

clear all, close all, clc;

addpath('../src');
addpath('../data');


filenames = {'tetrahedron';...
             'cube';...
             'octahedron';...
             'icosahedron';...
             'dodecahedron';...
             'dodecahedron2';...
             'disk';...
             'torus_light';...                     
             'meshed_mtlb_logo';...
             'kitten';...
             'Gargoyle_3k';...                        
             };

id = 4;         
filename = strcat(cell2mat(filenames(id,1)),'.mat');         
load(filename);

[V,T] = oversample_mesh(V,T); % 'default' / midedge or 'centre'
plot_mesh(V,T);