% test unite_meshes

clear all, close all, clc;

addpath('../src');
addpath('../data');


filenames = {'tetrahedron';...
             'cube';...
             'octahedron';...
             'icosahedron';...
             'dodecahedron';...
             'dodecahedron2';...
             'disk';...
             'torus_light';...
             'torus';...
             'geoid_lvl_16';...
             'meshed_mtlb_logo';...
             'kitten';...
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k';...             
             };
             
filename1 = strcat(cell2mat(filenames(4,1)),'.mat');         
load(filename1);

V1 = V;
T1 = T;

filename2 = strcat(cell2mat(filenames(1,1)),'.mat');         
load(filename2);

V2 = V + 2;
T2 = T;

[V,T] = unite_meshes(V1,V2,T1,T2);
plot_mesh(V,T);