% test upsample_mesh

clc;

addpath(genpath('../../src'));
addpath('../../data');


filenames = {'tetrahedron';...
             'cube';...
             'octahedron';...
             'icosahedron';...
             'dodecahedron';...
             'dodecahedron2';...
             'disk';...
             'sinusoidal_dodecahedron_MR';...
             'torus_light';...                     
             'meshed_mtlb_logo';...
             'kitten';...
             'Gargoyle_3k';...                        
             };

         
id = 8;         
filename = strcat(cell2mat(filenames(id,1)),'.mat');         
load(filename);
plot_mesh(V,T);

% Upsample the whole mesh
[V,T] = upsample_mesh(V,T); % 'default' / midedge or 'centre'
plot_mesh(V,T);

% % Upsample one triangle subset only; method = 'centre'
% load(filename);
% [V,T] = upsample_mesh(V,T,'centre',1:floor(0.5*height(T))); % restricted to the first half of the triangle set
% plot_mesh(V,T);
