% test vertex_normals

clc;

addpath(genpath('../../src'));
addpath('../../data');


filenames = {'tetrahedron';...
             'cube';...
             'octahedron';...
             'icosahedron';...
             'dodecahedron_trimesh_regular';...
             'geoid_lvl4';...
             'meshed_mtlb_logo';...
             'kitten';...
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k'};

filename = strcat(cell2mat(filenames(5,1)),'.mat');         
load(filename);

% % If needed
% T = reorient_all_faces_coherently(V,T);
% T = flip_faces_orientation(T);

ngb_degre = 1;
show_vertex_normals(V,T,ngb_degre);