% test face_normals

clc;

addpath(genpath('../../src'));
addpath('../../data');


filenames = {'tetrahedron';...
             'cube';...
             'octahedron';...
             'icosahedron';...
             'dodecahedron_trimesh_regular';...
             'dodecahedron_trimesh_optim';...
             'disk';...
             'torus_light';...
             'torus';...
             'geoid_lvl4';...
             'meshed_mtlb_logo';...
             'kitten';...
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k';...             
             };

fid = 10;         
filename = strcat(cell2mat(filenames(fid,1)),'.mat');         
load(filename);

% % If needed
% T = reorient_all_faces_coherently(V,T);
% T = flip_faces_orientation(T);

show_face_normals(V,T);