% test mesh_curvature

clc;

addpath(genpath('../../src'));
addpath('../../data');


filenames = {'Reuleaux_tetrahedron';...
             'sinico';...                   
             'torus_light';...
             'torus';...                          
             'kitten';...             
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k';...
             'Armadillo_20k';...
             'sinus_dodeca';...       
             'Archi_spiral';...
             'Log_spiral';...             
             'Fermat_spiral'};
                 
    
fid = 9;
filename = strcat(cell2mat(filenames(fid,1)),'.mat');         
load(filename);

ngb_degre = 1;
N = vertex_normals(V,T,ngb_degre,'raw');
curvature = mesh_curvature(V,T,N,ngb_degre,'mean');
show_mesh_curvature(V,T,curvature);