% test mesh_curvature

clc;

addpath(genpath('../../src'));
addpath('../../data');


filenames = {'Reuleaux_tetrahedron';...
             'sinico';...                   
             'torus_light';...
             'torus';...                          
             'kitten';...             
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k';...
             'bunny_16k';...
             'Cthulhu_skull';...
             'Right_hemisphere'};
                 
% 'sinus_dodeca';...       
% 'log_spiral';...
% 'Archimede_spiral';...
% 'Fermat_spiral';...         

filename = strcat(cell2mat(filenames(3,1)),'.mat');         
load(filename);

ngb_degre = 1;
N = vertex_normals(V,T,ngb_degre,'raw');
curvature = mesh_curvature(V,T,N,ngb_degre,'mean');
show_mesh_curvature(V,T,curvature);