% Test dual_of_trimesh

clc;

addpath(genpath('../../src'));
addpath('../../data');


filenames = {'tetrahedron';...
             'cube';...
             'octahedron';...
             'icosahedron';...
             'dodecahedron_trimesh_regular';...
             'dodecahedron_trimesh_optim';...
             'disk';...
             'concave_Reuleaux_tetrahedron';...
             'torus_light';...
             'torus';...
             'geoid_lvl4';...
             'meshed_mtlb_logo';...
             'kitten';...
             'Gargoyle_3k';...
             'Gargoyle_5k';...
             'Armadillo_10k'};

         
fid = 11;         
filename = strcat(cell2mat(filenames(fid,1)),'.mat');         
load(filename);

plot_mesh(V,T);

[V_dual,T_dual] = dual_of_trimesh(V,T);
plot_mesh(V_dual,T_dual);       